version: '2'

services:
  drone-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: woodpeckerci/woodpecker-server:local
    ports:
      - 8000:8000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    environment:
      - DRONE_OPEN=true
      - DRONE_ADMIN=laszlocph
      - DRONE_HOST=${HOST}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=${GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${GITHUB_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
  drone-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    image: woodpeckerci/woodpecker-agent:local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_MAX_PROCS=2